name: synctra_sdk
description: SDK Flutter professionnel pour la gestion des liens dynamiques, deferred deep linking et analytics. Alternative moderne à Firebase Dynamic Links.
version: 1.0.0
homepage: https://github.com/zenderock/synctra_sdk
repository: https://github.com/zenderock/synctra_sdk
issue_tracker: https://github.com/zenderock/synctra_sdk/issues
documentation: https://docs.synctra.link

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  http: ^1.1.0
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.1
  package_info_plus: ^4.2.0
  device_info_plus: ^9.1.1
  crypto: ^3.0.3
  uuid: ^4.1.0
  meta: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mockito: ^5.4.2
  build_runner: ^2.4.7

flutter:
